# -*- coding: utf-8 -*-
"""lab3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MWhJKgmUKzuGbPxpTLTISBCf2BvPMb_p

##Task 1
"""

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split, Subset

SEED = 42
BATCH_SIZE = 32

transform = transforms.ToTensor()
dataset = datasets.CIFAR10(root="./data", train=True, download=True, transform=transform)

# --- Binary (cat vs dog)
binary_classes = ["cat", "dog"]
binary_labels = [dataset.classes.index("cat"), dataset.classes.index("dog")]

binary_indices = [i for i, (_, y) in enumerate(dataset) if y in binary_labels]
binary_subset = Subset(dataset, binary_indices)

train_size = int(0.7 * len(binary_subset))
test_size = len(binary_subset) - train_size
gen = torch.Generator().manual_seed(SEED)

binary_train, binary_test = random_split(binary_subset, [train_size, test_size], generator=gen)
binary_loader = DataLoader(binary_train, batch_size=BATCH_SIZE, shuffle=True)

images, labels = next(iter(binary_loader))
print("Binary classes:", binary_classes)
print("Number of classes:", 2)
print("Batch shape:", images.shape)

# --- Multiclass (airplane, ship, truck)
multi_classes = ["airplane", "ship", "truck"]
multi_labels = [dataset.classes.index(c) for c in multi_classes]

multi_indices = [i for i, (_, y) in enumerate(dataset) if y in multi_labels]
multi_subset = Subset(dataset, multi_indices)

train_size = int(0.7 * len(multi_subset))
test_size = len(multi_subset) - train_size

multi_train, multi_test = random_split(multi_subset, [train_size, test_size], generator=gen)
multi_loader = DataLoader(multi_train, batch_size=BATCH_SIZE, shuffle=True)

images, labels = next(iter(multi_loader))
print("Multiclass classes:", multi_classes)
print("Number of classes:", len(multi_classes))
print("Batch shape:", images.shape)

"""##Task 2"""

import matplotlib.pyplot as plt
from torchvision import datasets, transforms
import torch

# ----- 1) Dataset WITHOUT normalization (only resize + tensor)
transform_before = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.ToTensor()
])

dataset_before = datasets.CIFAR10(root="./data", train=True, download=True, transform=transform_before)

img_before, label = dataset_before[0]

# ----- 2) Dataset WITH normalization
MEAN = (0.5, 0.5, 0.5)
STD = (0.5, 0.5, 0.5)

transform_after = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.ToTensor(),
    transforms.Normalize(MEAN, STD) #x=(x-mean)/std
])

dataset_after = datasets.CIFAR10(root="./data", train=True, download=True, transform=transform_after)

img_after, label = dataset_after[0]

# ----- Denormalize for visualization
img_after_vis = img_after.clone()
for c in range(3):
    img_after_vis[c] = img_after_vis[c] * STD[c] + MEAN[c]

# ----- Plot
plt.figure(figsize=(8,4))

plt.subplot(1,2,1)
plt.imshow(img_before.permute(1,2,0))
plt.title("Before preprocessing")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(img_after_vis.permute(1,2,0))
plt.title("After preprocessing (denormalized)")
plt.axis("off")

plt.show()

"""##Task 3

"""

import torch.nn as nn

class BaselineCNN(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Conv2d(3, 16, 3, padding=1), #(h+2p-k)/s +1 (16,32,32)
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(16, 32, 3, padding=1), #(32,16,16)
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Flatten(), #vector 2048
            nn.Linear(32*8*8, 128),
            nn.ReLU(),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        return self.model(x)

model = BaselineCNN(num_classes=3)#airplane, ship , truck
print(model)

total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Trainable parameters:", total_params)

"""##Task 4

"""

import torch.optim as optim
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Create a mapping from original multi_labels to a 0-indexed range
# multi_labels = [0, 8, 9] (airplane, ship, truck)
# We want to map them to [0, 1, 2] for a 3-class model
label_map = {original_label: new_index for new_index, original_label in enumerate(multi_labels)}

for epoch in range(5):
    model.train()
    for x, y_original in multi_loader:
        # Remap the target labels
        y = torch.tensor([label_map[label.item()] for label in y_original], device=y_original.device)

        optimizer.zero_grad()
        outputs = model(x)
        loss = criterion(outputs, y)
        loss.backward()
        optimizer.step()

# Evaluation
model.eval()
all_preds = []
all_labels_remapped = [] # Store remapped labels for evaluation

with torch.no_grad():
    for x, y_original in multi_loader:
        # Remap the target labels for evaluation
        y_remapped = torch.tensor([label_map[label.item()] for label in y_original], device=y_original.device)

        outputs = model(x)
        preds = outputs.argmax(1) # These predictions will be 0, 1, 2

        all_preds.extend(preds.cpu().numpy())
        all_labels_remapped.extend(y_remapped.cpu().numpy())

print("Accuracy:", accuracy_score(all_labels_remapped, all_preds))
print("Precision:", precision_score(all_labels_remapped, all_preds, average="macro"))
print("Recall:", recall_score(all_labels_remapped, all_preds, average="macro"))
print("F1:", f1_score(all_labels_remapped, all_preds, average="macro"))

"""##Task 5"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(all_labels_remapped, all_preds)

sns.heatmap(cm, annot=True, fmt="d")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()

"""##Task 6

"""

class ImprovedCNN(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Flatten(),
            nn.Linear(128*4*4, 256),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        return self.model(x)

"""##Task 7"""

optimizer1 = optim.Adam(model.parameters(), lr=0.001)
optimizer2 = optim.SGD(model.parameters(), lr=0.01)
